format = """
[\uE0B6](white)$username$hostname[\uE0B4](bg:blue fg:white)\
$directory[\uE0B4](bg:purple fg:blue)\
$git_branch$gitstatus[\uE0B4](purple)\
$fill[\uE0B6](bg:white fg:black)$time[\uE0B4](bg:white fg:black)
$character """


add_newline = false
command_timeout = 1000


[aws]
symbol = "  "

[character]
success_symbol = "[ \ufcb5](green)"
error_symbol = "[ \ufcb5](red)"

[cmd_duration]
min_time = "2_000"
format = "took [$duration]($style) "
style = "yellow"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 3
format = "[ \uF413 $path]($style)[$read_only]($read_only_style)"
style = "bg:blue fg:white"
read_only = " "
truncation_symbol = "../"
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

[git_branch]
format = "[ \ue709 $symbol$branch]($style)"
style = "bg:purple fg:white"
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bg:purple fg:purple"
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_only = true
format = "[@$hostname]($style)"
style = "bg:white fg:black"

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[status]
disabled = false
format = '[$symbol]($style)'
symbol = " ✘"
success_symbol = " ✔"
style = "red"

[swift]
symbol = "ﯣ "

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M:%S"
utc_time_offset = "+10"
style = "bg:white fg:black"

[username]
style_user = "bg:white fg:black"
style_root = "bg:white fg:black "
format = "[ \uf2c0$user]($style)"
show_always = false
