format = """
[ ](white)$all
[ ](white)
[ ](white)$character """

right_format = """
[ ](white)$time
[ ](white)
[ ](white)$character """

add_newline = false
command_timeout = 1000


[aws]
symbol = "  "

[character]
success_symbol = "(green)"
error_symbol = "(green)"
vicmd_symbol = "(purple)"

[cmd_duration]
min_time = "2_000"
format = "took [$duration]($style) "
style = "yellow"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bg:blue fg:white"
read_only = " "
truncation_symbol = "../"
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bg:purple fg:white"
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bg:purple fg:purple"
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_only = true
format = "[@$hostname]($style)"
style = "bg:dark-green fg:white"

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[status]
disabled = false
format = '[ $symbol]($style) '
symbol = "✘ "
success_symbol = "✔ "
style = "red"

[swift]
symbol = "ﯣ "

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M:%S"
utc_time_offset = "+10"

[username]
style_user = "bg:dark-yellow fg:white"
style_root = "gb:dark-red fg:white "
format = "[$user]($style)"
show_always = false
