format = """
[\uE0B6](green)$sudo\
[\uE0B6](bg:green fg:white)$username$hostname[\uE0B4](bg:blue fg:white)\
$directory[\uE0B4](bg:purple fg:blue)\
$git_branch$gitstatus$git_state[\uE0B4](purple)\
$fill\
[\uE0B6](black)$status\
[\uE0B6](bg:black fg:yellow)$cmd_duration\
[\uE0B6](bg:yellow fg:white)$time[\uE0B4](white)
$linebreak\
$character
"""


add_newline = false
command_timeout = 1000


[character]
success_symbol = "[ \uf6d7](green)"
error_symbol = "[ \uf6d7](red)"
vicmd_symbol = "[ \uf6d7](green)"

[cmd_duration]
min_time = "2_000"
format = "[\ufa1e $duration]($style)"
style = "bg:yellow fg:black"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 3
format = "[ \uF413 $path]($style)[$read_only]($read_only_style)"
style = "bg:blue fg:white"
read_only = " \uf023"
truncation_symbol = "../"
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[docker_context]
symbol = "\uf308 "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

[git_branch]
format = "[ \uf113 $symbol$branch]($style)"
style = "bg:purple fg:white"
symbol = "\ue725 "

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bg:purple fg:purple"
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bg:purple fg:purple"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_only = true
format = "[@$hostname]($style)"
style = "bg:white fg:black"

[java]
symbol = " "

[julia]
symbol = " "

[line_break]
disabled = false

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[status]
disabled = false
format = '[$symbol]($style)'
symbol = "✘"
success_symbol = "✔"
style = "red"

[sudo]
format = "[ $symbol]($style)"
style = "bg:green fg:black"
symbol = "\uf5e7 "
disabled = false

[time]
format = "[\uf64f $time]($style)"
disabled = false
time_format = "%Y-%m-%d %H:%M:%S"
utc_time_offset = "local"
style = "bg:white fg:black"

[username]
style_user = "bg:white fg:black"
style_root = "bg:white fg:black "
format = "[ \uf2c0$user]($style)"
show_always = false
