format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$status\
$cmd_duration\
$line_break\
$character
"""

add_newline = false
command_timeout = 1000
right_format = time

[aws]
symbol = "  "

[character]
success_symbol = "[](green)"
error_symbol = "[](green)"
vicmd_symbol = "[](purple)"

[cmd_duration]
min_time = "2_000"
format = "took [$duration]($style) "
style = "yellow"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " "
truncation_symbol = "../"
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "purple"
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "purple"
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_only = true
format = "[@$hostname]($style) in "
style = "green"

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[status]
disabled = false
format = '[ $symbol]($style) '
symbol = "✘ "
success_symbol = "✔ "
style = "red"

[swift]
symbol = "ﯣ "

[username]
style_user = "yellow"
style_root = "red"
format = "[$user]($style)"
show_always = false
